### ISSUE TITLE
Training on SSD terminated due to 'thrust::system::system_error'

### ISSUE THREAD

**Issue by leewaymay** [chainer/chainercv#567] opened 2018-04-13 05:26 UTC
I encountered an issue when I was using my own dataset to train SSD. And I have the following error after I trained the first 20 iterations.
`terminate called after throwing an instance of 'thrust::system::system_error'`
`what():  merge_sort: failed to synchronize: an illegal memory access was encountered`
I used the same dataset to train Faster-rCNN and it has no problem.
I trained with the VOC dataset and the training code works.
I checked the `cupy.sort()` method, and I can successfully call this method.
`asd = np.array([1, 23, 343, 3424, 134])
asd = cupy.array(asd)
cupy.sort(asd)
`
The output is 
`array([   1,   23,  134,  343, 3424])`

I don't know what cause this issue. Could anyone help me?

**Comment by fukatani** [comment] 2018-05-06 14:07
Do you succeed to train by `chainercv/examples/ssd/train.py`?

And do you use multi GPU?
If yes, you also had better to confirm whether `train_multi.py` works or not.

**Comment by Hakuyume** [comment] 2018-05-18 07:51
Please try `train.py` with Pascal VOC, first.

**Comment by doiken23** [comment] 2018-05-28 00:29
I have encountered same problem.
I could train with VOCDataset, but I got  `'thrust::system::system_error'`  when I use my own dataset.
Is there any possible cause?

Best regards.

**Comment by Hakuyume** [comment] 2018-05-28 03:42
Please check the number of instances per image.

**Comment by doiken23** [comment] 2018-05-29 01:29
Do you mean that if the number of instances is 0, the error occur?

I have checked that there is no image that doesn't have instances.

**Comment by Hakuyume** [comment] 2018-05-29 01:40
> I have checked that there is no image that doesn't have instances.

I see. Could you report this issue to CuPy repository?

**Comment by leewaymay** [comment] 2018-06-09 06:16
I successed with the VOC dataset and I only have one GPU so I didn't try train_multi.py code.

I haven't tried the SSD after this issue occured. But I suspect that the reason might be there can be no instance in one of the training images in my dataset. Thought all images in my dataset have at least one instance, after transform in the training script, the cropped images might contain no instance.

**Comment by knorth55** [comment] 2018-09-08 16:32
can we close this issue?

**Closed** 2018-09-08 22:50 UTC
Labels: bug

**Comment by Furlly** [comment] 2019-07-05 06:43
Same problems, since I have a lot of images without instance in it, will the error may resulted by this, and why?
So how can I train SSD with images with no instance?
Looking forward for help.

**Comment by Furlly** [comment] 2019-07-17 03:17
> Please check the number of instances per image.

Could you please tell me the reason why no instance images will lead to this error?

**Comment by Hakuyume** [comment] 2019-07-17 06:30
Since I couldn't reproduce that error in my environment, I don't know the actual reason. Even if I removed all instances from the training dataset, the train script worked. This is just a guess.
