### ISSUE TITLE
chainercv.transforms.scale does not work with chainer.iterators.MultiprocessIterator

### ISSUE THREAD

**Issue by jinjiren** [chainer/chainercv#386] opened 2017-08-09 10:22 UTC
Either `random_crop` or `center_crop` will cause the training even not start when using `MultiprocessIterator`. However, if I change to use `SerialIterator`, it will work just fine.

Haven't tested other transforms, but could you provide some insights about why this happens?

**Comment by Hakuyume** [comment] 2017-08-09 11:17
Could you give me a simple code that reproduce this problem?

I tried following code. It worked well on my environment.
```
import numpy as np
import chainer
from chainercv import transforms


class Model(chainer.Link):

    def __call__(self, x):
        return chainer.functions.sum(x)


def transform(in_data):
    img = in_data
    img = transforms.random_crop(img, (4, 4))
    return img


dataset = np.random.uniform(size=(10, 3, 10, 10)).astype(np.float32)
dataset = chainer.datasets.TransformDataset(dataset, transform)
iter_ = chainer.iterators.MultiprocessIterator(dataset, 2)

model = Model()
optimizer = chainer.optimizers.MomentumSGD()
optimizer.setup(model)

updater = chainer.training.StandardUpdater(iter_, optimizer)
trainer = chainer.training.Trainer(updater, (1, 'epoch'))
trainer.extend(chainer.training.extensions.ProgressBar())

trainer.run()
```

**Comment by yuyu2172** [comment] 2017-08-09 23:29
The code @Hakuyume  posted exits gracefully.

I modified the code to conduct more computationally intensive operation in transform.

```
import numpy as np
import chainer
from chainercv import transforms


class Model(chainer.Link):

    def __call__(self, x):
        return chainer.functions.sum(x)


def transform(in_data):
    img = in_data
    print('enter tranform')
    img = transforms.scale(img, 256)
    img = transforms.random_crop(img, (224, 224))
    return img


dataset = np.random.uniform(size=(10, 3, 300, 300)).astype(np.float32)
dataset = chainer.datasets.TransformDataset(dataset, transform)
iter_ = chainer.iterators.MultiprocessIterator(dataset, 2)

model = Model()
optimizer = chainer.optimizers.MomentumSGD()
optimizer.setup(model)

updater = chainer.training.StandardUpdater(iter_, optimizer)
trainer = chainer.training.Trainer(updater, (1, 'epoch'))

trainer.run()
```

This time, it hangs after finish iterating for 1 epoch.
It has a problem with `iterator.finalize`.

I can confirm that `MultiprocessIterator` has a bug.
However, I can not reproduce a situation when nothing starts.

**Comment by Hakuyume** [comment] 2017-08-10 00:24
I confirmed that @yuyu2172 's code started training and hanged after all iterations are finished (1 epoch).

**Comment by zori** [comment] 2017-08-10 01:58
Though the `MultiprocessIterator` probably has issues https://github.com/chainer/chainer/issues/3075, changing to a different chainer + cupy combination might be a work-around for you.

**Comment by sharpstill** [comment] 2017-08-10 05:02
@yuyu2172 what happened if I raise IndexError inside get_example function?(method in subclass of chainer.dataset.DatasetMixin)

**Comment by yuyu2172** [comment] 2017-08-10 05:12
In that case, the processes just hang...

**Comment by jinjiren** [comment] 2017-08-10 05:15
```
import numpy as np
import chainer
from chainercv import transforms


class Model(chainer.Link):

    def __call__(self, x):
        print('enter training')
        return chainer.functions.sum(x)


def closure():
    i = 0
    def transform(in_data):
        nonlocal i
        i += 1
        print('enter tranform')
        print(i)
        img = in_data
        img = transforms.scale(img, 256)
        img = transforms.random_crop(img, (224, 224))
        return img
    return transform

transform = closure()
dataset = np.random.uniform(size=(10, 3, 300, 200)).astype(np.float32)
#dataset = np.random.uniform(size=(10, 3, 300, 300)).astype(np.float32)
dataset = chainer.datasets.TransformDataset(dataset, transform)
iter_ = chainer.iterators.MultiprocessIterator(dataset, 1)

model = Model()
optimizer = chainer.optimizers.MomentumSGD()
optimizer.setup(model)

updater = chainer.training.StandardUpdater(iter_, optimizer)
trainer = chainer.training.Trainer(updater, (1, 'epoch'))

trainer.run()
```
try this, actually just changed the image size...
if `H` > 256 and `W` < 256, the process will hang in my environment.

**Comment by jinjiren** [comment] 2017-08-10 05:20
If I interrupt (using ipython notebook), the traceback is like this:
```
enter tranform
1
enter tranform
2
enter training
Process Process-71:
Process Process-70:
Process Process-69:
Process Process-74:
Process Process-68:
Process Process-72:
Process Process-73:
Process Process-67:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
Process Process-66:
Traceback (most recent call last):
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/chainer-3.0.0b1-py3.6.egg/chainer/iterators/multiprocess_iterator.py", line 386, in _worker
    cnt, mem_index, index = in_queue.get()
Traceback (most recent call last):
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/chainer-3.0.0b1-py3.6.egg/chainer/iterators/multiprocess_iterator.py", line 386, in _worker
    cnt, mem_index, index = in_queue.get()
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/chainer-3.0.0b1-py3.6.egg/chainer/iterators/multiprocess_iterator.py", line 386, in _worker
    cnt, mem_index, index = in_queue.get()
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/chainer-3.0.0b1-py3.6.egg/chainer/iterators/multiprocess_iterator.py", line 386, in _worker
    cnt, mem_index, index = in_queue.get()
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/queues.py", line 93, in get
    with self._rlock:
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/queues.py", line 93, in get
    with self._rlock:
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/chainer-3.0.0b1-py3.6.egg/chainer/iterators/multiprocess_iterator.py", line 386, in _worker
    cnt, mem_index, index = in_queue.get()
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/queues.py", line 93, in get
    with self._rlock:
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/queues.py", line 93, in get
    with self._rlock:
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/queues.py", line 93, in get
    with self._rlock:
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/chainer-3.0.0b1-py3.6.egg/chainer/iterators/multiprocess_iterator.py", line 386, in _worker
    cnt, mem_index, index = in_queue.get()
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/chainer-3.0.0b1-py3.6.egg/chainer/iterators/multiprocess_iterator.py", line 386, in _worker
    cnt, mem_index, index = in_queue.get()
KeyboardInterrupt
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/queues.py", line 93, in get
    with self._rlock:
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/chainer-3.0.0b1-py3.6.egg/chainer/iterators/multiprocess_iterator.py", line 386, in _worker
    cnt, mem_index, index = in_queue.get()
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/chainer-3.0.0b1-py3.6.egg/chainer/iterators/multiprocess_iterator.py", line 386, in _worker
    cnt, mem_index, index = in_queue.get()
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/queues.py", line 93, in get
    with self._rlock:
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/queues.py", line 93, in get
    with self._rlock:
KeyboardInterrupt
Process Process-75:
Process Process-77:
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
KeyboardInterrupt
Process Process-78:
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
Process Process-79:
KeyboardInterrupt
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
Process Process-76:
Process Process-80:
KeyboardInterrupt
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/chainer-3.0.0b1-py3.6.egg/chainer/iterators/multiprocess_iterator.py", line 386, in _worker
    cnt, mem_index, index = in_queue.get()
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/chainer-3.0.0b1-py3.6.egg/chainer/iterators/multiprocess_iterator.py", line 386, in _worker
    cnt, mem_index, index = in_queue.get()
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/queues.py", line 93, in get
    with self._rlock:
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/chainer-3.0.0b1-py3.6.egg/chainer/iterators/multiprocess_iterator.py", line 386, in _worker
    cnt, mem_index, index = in_queue.get()
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/queues.py", line 93, in get
    with self._rlock:
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/queues.py", line 93, in get
    with self._rlock:
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/chainer-3.0.0b1-py3.6.egg/chainer/iterators/multiprocess_iterator.py", line 386, in _worker
    cnt, mem_index, index = in_queue.get()
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/chainer-3.0.0b1-py3.6.egg/chainer/iterators/multiprocess_iterator.py", line 386, in _worker
    cnt, mem_index, index = in_queue.get()
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/chainer-3.0.0b1-py3.6.egg/chainer/iterators/multiprocess_iterator.py", line 386, in _worker
    cnt, mem_index, index = in_queue.get()
KeyboardInterrupt
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/queues.py", line 93, in get
    with self._rlock:
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/queues.py", line 93, in get
    with self._rlock:
KeyboardInterrupt
KeyboardInterrupt
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/queues.py", line 93, in get
    with self._rlock:
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
  File "/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-9-c3c6d38035dc> in <module>()
     37 trainer = chainer.training.Trainer(updater, (1, 'epoch'))
     38 
---> 39 trainer.run()

/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/chainer-3.0.0b1-py3.6.egg/chainer/training/trainer.py in run(self, show_loop_exception_msg)
    308                 self.observation = {}
    309                 with reporter.scope(self.observation):
--> 310                     update()
    311                     for name, entry in extensions:
    312                         if entry.trigger(self):

/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/chainer-3.0.0b1-py3.6.egg/chainer/training/updater.py in update(self)
    221 
    222         """
--> 223         self.update_core()
    224         self.iteration += 1
    225 

/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/chainer-3.0.0b1-py3.6.egg/chainer/training/updater.py in update_core(self)
    225 
    226     def update_core(self):
--> 227         batch = self._iterators['main'].next()
    228         in_arrays = self.converter(batch, self.device)
    229 

/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/chainer-3.0.0b1-py3.6.egg/chainer/iterators/multiprocess_iterator.py in __next__(self)
     76                 self._invoke_prefetch()
     77 
---> 78         batch = self._get()
     79         self._invoke_prefetch()  # prefetch for the next iteration
     80         return batch

/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/chainer-3.0.0b1-py3.6.egg/chainer/iterators/multiprocess_iterator.py in _get(self)
    214         batch = []
    215         for _ in six.moves.range(self.batch_size):
--> 216             d = self._ordered_data_queue.get()
    217             if d is self._last_signal:
    218                 break

/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/queue.py in get(self, block, timeout)
    162             elif timeout is None:
    163                 while not self._qsize():
--> 164                     self.not_empty.wait()
    165             elif timeout < 0:
    166                 raise ValueError("'timeout' must be a non-negative number")

/home/jin/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/threading.py in wait(self, timeout)
    293         try:    # restore state no matter what (e.g., KeyboardInterrupt)
    294             if timeout is None:
--> 295                 waiter.acquire()
    296                 gotit = True
    297             else:

KeyboardInterrupt: 
```

**Comment by yuyu2172** [comment] 2017-08-10 05:46
It iterated 11 times in my environment.

```
enter tranform  
1               
enter tranform  
enter training  
2               
enter training  
enter tranform  
2               
enter training  
enter tranform  
2               
enter training  
enter tranform  
2               
enter training  
enter tranform  
2               
enter training  
enter tranform  
2               
enter training  
enter tranform  
2               
enter training  
enter tranform  
2               
enter training  
enter tranform  
3               
enter training  
enter tranform  
3               
```

Have you updated the version of ChainerCV to the lastest?

**Comment by jinjiren** [comment] 2017-08-10 05:54
@yuyu2172 I'm using chainer (3.0.0b1), chainercv (0.6.0), and copy (2.0.0b1)

**Comment by Hakuyume** [comment] 2017-08-10 07:27
I tried @jinjiren 's code with chainer (3.0.0b1), cupy (2.0.0b1) and chainercv (0.6.0). It trained the model for 10 iterations and hanged.

**Comment by jinjiren** [comment] 2017-08-10 07:37
@Hakuyume It's strange, on my machine, it can only produce 2 transform and enter training once..
<img width="628" alt="2017-08-10 16 35 14" src="https://user-images.githubusercontent.com/8536399/29159553-f09d9db0-7de9-11e7-9bda-6f39ad16c1a6.png">

**Comment by Hakuyume** [comment] 2017-08-10 07:46
Here is my environment. Note that `cv2` is available but not shown below because I installed opencv without pip.
```
$ pip list
chainer (3.0.0b1)
chainercv (0.6.0)
cupy (2.0.0b1)
cycler (0.10.0)
Cython (0.26)
filelock (2.0.11)
matplotlib (2.0.2)
mock (2.0.0)
nose (1.3.7)
numpy (1.13.1)
olefile (0.44)
pbr (3.1.1)
Pillow (4.2.1)
pip (9.0.1)
protobuf (3.3.0)
pyparsing (2.2.0)
python-dateutil (2.6.1)
pytz (2017.2)
setuptools (28.8.0)
six (1.10.0)
```

Here is the result of your code (https://github.com/chainer/chainercv/issues/386#issuecomment-321452860)
```
enter tranform
1
enter training
enter tranform
2
enter training
enter tranform
2
enter training
enter tranform
2
enter training
enter tranform
2
enter training
enter tranform
2
enter training
enter tranform
2
enter training
enter tranform
2
enter training
enter tranform
2
enter training
enter tranform
2
enter training
enter tranform
2
(hang)
```

**Comment by Hakuyume** [comment] 2017-08-10 07:48
@jinjiren Are you using cv2 (opencv)? Can you reproduce your problem without `transform.scale`?

**Comment by jinjiren** [comment] 2017-08-10 07:53
@Hakuyume I had cv2 installed, using conda, the version is 3.2.0. Actually I cannot reproduce the problem without using `transoform.scale`. If only using the `random_crop`, I had the similar output with yours, just hang after 10 iterations (1 epoch).

**Comment by jinjiren** [comment] 2017-08-10 07:57
Maybe it's better to change the `random_crop` in the title of this issue to `scale`?

**Comment by Hakuyume** [comment] 2017-08-10 07:58
@jinjiren Could you try your code with `cv2` disabled (uninstalled)? I mean running `transform.scale` with Pillow backend.

**Comment by Hakuyume** [comment] 2017-08-10 07:59
> Maybe it's better to change the random_crop in the title of this issue to scale?

If same problem occurs without `random_crop`, please rename this issue.

**Comment by jinjiren** [comment] 2017-08-10 08:03
@Hakuyume The output is similar to yours after uninstalled opencv.
<img width="638" alt="2017-08-10 16 59 57" src="https://user-images.githubusercontent.com/8536399/29160512-7b4bbff2-7ded-11e7-8778-9f712fd73673.png">

**Comment by Hakuyume** [comment] 2017-08-10 08:25
@jinjiren I think it is python or cv2 's bug. `cv2` sometimes hangs if it is used in subprocesses.

I experienced similar problem. At that time, I solved it by compiling opencv with TBB backend instead of pthread backend. However, I am not sure this solution works for you and compiling was a little bit hard.

**Comment by Hakuyume** [comment] 2017-08-10 08:44
@jinjiren Thank you for reporting and debugging. I close this issue because this is not ChainerCV's problem.

**Closed by Hakuyume** 2017-08-10 08:44 UTC

**Comment by jinjiren** [comment] 2017-08-10 08:51
@Hakuyume I understand, but even using PIL instead of cv2, the program will still hang after the 1st epoch training, is this the problem of `MultiprocessIterator`?

**Comment by Hakuyume** [comment] 2017-08-10 09:10
@jinjiren I think so. I could reproduce it without ChainerCV.
```
import numpy as np
import chainer


class Model(chainer.Link):

    def __call__(self, x):
        print('called')
        return chainer.functions.sum(x)

dataset = np.random.uniform(size=(10, 3, 300, 300)).astype(np.float32)
iter_ = chainer.iterators.MultiprocessIterator(dataset, 1)

model = Model()
optimizer = chainer.optimizers.MomentumSGD()
optimizer.setup(model)

updater = chainer.training.StandardUpdater(iter_, optimizer)
trainer = chainer.training.Trainer(updater, (1, 'epoch'))

trainer.run()
```

@yuyu2172 you said `I can confirm that MultiprocessIterator has a bug.` (https://github.com/chainer/chainercv/issues/386#issuecomment-321408989). Is it known issue?

**Comment by yuyu2172** [comment] 2017-08-10 10:05
I am not sure if this problem is widely known.
I personally encountered this several times.

**Comment by furushchev** [comment] 2018-02-03 15:48
Maybe too late to discuss on it.
It looks this problem is caused by dead lock in thread.
For example, let a computer has 10 available threads, `MultiprocessIterator` creates up to 10 threads and call `Dataset` functions.
In the `Dataset` functions, if there is at least one function that tries to create another thread (e.g. TBB, OpenMP, GCD and so on), a dead lock will happen.

I personally see the same problem when I train SSD with `MultiprocessIterator`, it stops in the line of `cv2.resize`
(at https://github.com/chainer/chainercv/blob/master/chainercv/links/model/ssd/transforms.py#L284 )
which uses concurrent computation internally.
I then add `cv2.setNumThreads(0)` to disable threading on opencv functions, and could see it works without dead lock.

**Comment by LaurentBerder** [comment] 2018-02-28 08:25
I've seen a similar situation with SSD hanging whenever `MultiprocessIterator` was used ( [#4412](https://github.com/chainer/chainer/issues/4412)).
I managed to solve this by assigning `shared_mem`, but it definitively looks like a bug.

**Comment by hiramekun** [comment] 2018-03-29 22:02
I encountered the same situation when training SSD with `MultiProcessIterator`, and solve by `cv2.setNumThreads(0)`, thanks to @furushchev .

**Comment by LaurentBerder** [comment] 2018-03-30 16:50
Doesn't that essentially mean that you're not using multiprocessing then?



On Mar 30, 2018 at 00:02, <Takaaki Hirano<mailto:notifications@github.com>> wrote:


I encountered the same situation when training SSD with MultiProcessIterator, and solve bycv2.setNumThreads(0), thanks to @furushchev<https://github.com/furushchev> .

-
