### ISSUE TITLE
A question about the Faster-RCNN model

### ISSUE THREAD

**Issue by 1991viet** [chainer/chainercv#244] opened 2017-06-04 15:32 UTC
Hi contributors,
Firstly, I would have to say that you already build a great framework. I have used it for 1 month, and it is much more convenient than many other ones. 
Secondly, I have questions about the Faster-RCNN model in the examples folder (https://github.com/chainer/chainercv/tree/master/examples/faster_rcnn), I hope you could clarify it to me.
Currently, I could run both training and test phases (train.py and demo.py) without any error. For the training, I just run it to make sure that it works, I have not run it completely. So my question is, assume that I do not modify anything from your code, if I run the train.py file, and use the final snapshot model as pretrained model for running the file demo.py with an image taken from VOC2007, does it work ? Does it produce the same output like when I run the demo.py with the default pretrained model you provide ?

An equivalent question could be like that, in the following link you provide several pretrained model
https://github.com/yuyu2172/share-weights/releases/
Specifically, for the faster-rcnn pretrained model, could I ask, where the file "**faster_rcnn_vgg16_voc07_2017_05_24.npz**" come from ? Is that the final snapshot model you have after running your own script completely once (and rename it), or do you have it by converting a pretrained caffe model or sth similar.

I just want to understand better the model.

Thank you so much

**Comment by yuyu2172** [comment] 2017-06-05 00:21
Thank you very much for using our library.

> Specifically, for the faster-rcnn pretrained model, could I ask, where the file "faster_rcnn_vgg16_voc07_2017_05_24.npz" come from ? Is that the final snapshot model you have after running your own script completely once (and rename it), or do you have it by converting a pretrained caffe model or sth similar.

We renamed the final snapshot model of `train.py`. More specifically, it was a weight converted from the previously released weight (`faster_rcnn_vgg16_voc07.npz`) to adopt to RGB color channel convention.

Unfortunately, the current code does not guarantee reproducible performance. The training outcome will fluctuate between 69.5mAP to 70.5mAP with the train and evaluation configurations used in `train.py`.

Also, [as stated in the README of the example](https://github.com/chainer/chainercv/tree/master/examples/faster_rcnn#difference-in-the-runtime-behaviour-from-the-original-code), runtime behavior has changed from caffe model by using float valued bounding box convention. Therefore, the conversion from the distributed caffemodel at py-faster-rcnn will not perform well.

**Comment by 1991viet** [comment] 2017-06-05 07:36
Thank you so much.
I run it completely. It does work.

**Comment by yuyu2172** [comment] 2017-06-05 07:41
Great to hear that!
Since the question is answered, I will close this issue.
Feel free to ask us anything again if you have one!

**Closed by yuyu2172** 2017-06-05 07:41 UTC
