### ISSUE TITLE
load ssd300 snapshot fail: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by mingxiaoh** [chainer/chainercv#553] opened 2018-04-03 03:51 UTC
Hello, 
when we tried to load ssd300 snapshot, we saw following problem, any suggestion for this issue? Thanks in advance.
--------------------------------------------------------------
$ python train.py --resume result/snapshot_iter_60000
Traceback (most recent call last):
  File "train.py", line 189, in <module>
    main()
  File "train.py", line 183, in main
    serializers.load_npz(args.resume, trainer)
  File "/home/mingxiao/pythonenv/py3-intel-chainer/lib/python3.5/site-packages/chainer/serializers/npz.py", line 187, in load_npz
    d.load(obj)
  File "/home/mingxiao/pythonenv/py3-intel-chainer/lib/python3.5/site-packages/chainer/serializer.py", line 83, in load
    obj.serialize(self)
  File "/home/mingxiao/pythonenv/py3-intel-chainer/lib/python3.5/site-packages/chainer/training/trainer.py", line 333, in serialize
    entry.extension.serialize(s[name])
  File "/home/mingxiao/pythonenv/py3-intel-chainer/lib/python3.5/site-packages/chainer/training/extensions/log_report.py", line 124, in serialize
    self._log = json.loads(log)
  File "/home/mingxiao/.local/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/home/mingxiao/.local/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/mingxiao/.local/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Hakuyume** [comment] 2018-04-04 15:47
I can't reproduce this error. What is the version of python, chainer, cupy and chainercv?

**Comment by Hakuyume** [comment] 2018-04-04 15:49
Also, please give me the version of example script. You can show the version by `git rev-parse HEAD`.

**Comment by mingxiaoh** [comment] 2018-04-08 02:48
thanks. 
chainercv commit: [master branch]7c0fb1484e726a5d4512f54883df80b43aa3bbea
chainer version: chainer-4.0.0a1
python version: 3.5.2
no cupy was used, we trained it on cpu.

**Comment by mingxiaoh** [comment] 2018-05-03 04:49
@fukatani Thanks. We save the snapshot per 10000 iterations,  it is expected that we can resume the test by load the saved snapshot.
I just uploaded one snapshot on https://github.com/mingxiaoh/chainercv/tree/master/examples/ssd/result.

**Comment by Hakuyume** [comment] 2018-05-03 05:57
@mingxiaoh I could reproduce the same error using your snapshot.
I found that your snapshot was broken. The following script can fix snapshot. Please try this.

```python
import argparse
import numpy as np

parser = argparse.ArgumentParser()
parser.add_argument('snapshot')
args = parser.parse_args()

snapshot = dict(np.load(args.snapshot))

key = 'extensions/LogReport/_log'
snapshot[key] = np.asarray(np.asscalar(snapshot[key]).decode())

with open(args.snapshot, mode='wb') as f:
    np.savez_compressed(f, **snapshot)
```

I will investigate why the snapshot was broken.

**Comment by mingxiaoh** [comment] 2018-05-10 04:27
@Hakuyume thanks.

**Comment by Hakuyume** [comment] 2018-05-28 05:31
Since I could not reproduce the issue in my environment, I close this issue.
@mingxiaoh If the same error occurs again, please reopen.

**Closed by Hakuyume** 2018-05-28 05:31 UTC
Labels: bug
